services:
  - type: web
    name: random-hello
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn djweb.wsgi:application"
    envVars:
      - key: WEB_CONCURRENCY
        value: 4